config/routes.rb
require "monban/constraints/signed_in"
require "monban/constraints/signed_out"

Rails.application.routes.draw do
  constraints Monban::Constraints::SignedIn.new do
    root "dashboards#show", as: :dashboard
  end

  constraints Monban::Constraints::SignedOut.new do
    root "sessions#new"
  end

  resources :categories, only: [:create, :destroy, :index, :show]
  resources :expenses, except: [:new]
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:show]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :expenses, -> { order(created_at: :desc) }

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  validates :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: 0 }
  validates :category, presence: true
  validates :name, presence: true

  delegate :name, to: :category, prefix: true
  delegate :name, to: :user, prefix: true

  def error_message
    errors.full_messages.join(", ") + "! D:"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :expenses, -> { order(created_at: :desc) }

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all.order(:name)
    @new_category = Category.new
  end

  def show
    @category = find_category
    @expenses = @category.expenses
  end

  def create
    @category = Category.new(category_params)

    if !@category.save
      flash[:error] = "#{@category.errors.full_messages.join(", ")}! D:"
    end

    redirect_to categories_path
  end

  def destroy
    @category = find_category
    @category.destroy
    flash[:alert] = "Deleted \"#{@category.name}.\""
    redirect_to categories_path
  end

  private

  def find_category
    Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @new_expense = Expense.new
    @expenses = Expense.all.order(created_at: :desc)
  end

  def show
    @expense = find_expense
  end

  def create
    expense = Expense.new(expense_params)

    if expense.save
      flash[:alert] = "Expense'd!"
    else
      flash[:error] = expense.error_message
    end

    redirect_to expenses_path
  end

  def edit
    @expense = find_expense
  end

  def update
    expense = find_expense

    if expense.update(expense_params)
      flash[:alert] = "Updated!"
    else
      flash[:error] = expense.error_message
    end

    redirect_to expense_path(expense)
  end

  def destroy
    find_expense.destroy
    flash[:alert] = "Deleted!"
    redirect_to expenses_path
  end

  private

  def find_expense
    Expense.find(params[:id])
  end

  def expense_params
    params.
      require(:expense).
      permit(:name, :amount, :category_id, :shared).
      merge(user: current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = find_user
  end

  private

  def find_user
    User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/categories/_category.html.erb
<div class="category">
  <p><%= link_to category.name, category %></p>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<%= render @categories %>

<%= form_for @new_category do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.submit "Create category" %>
  </div>
<% end %>

app/views/categories/show.html.erb
<h1>Category: <%= @category.name %></h1>

<%= render @expenses %>

<%= link_to "Delete category!", @category, method: :delete, data: { confirm: "Are you sure?" } %>

app/views/dashboards/show.html.erb
<h1>Your profile</h1>

<p>Hi, <%= current_user.name %>! Have you heard the Good News about FI/RE?</p>

<ul>
  <li><%= link_to "Manage categories", categories_path %></li>
  <li><%= link_to "Manage expenses", expenses_path %></li>
</ul>

app/views/expenses/_expense.html.erb
<div class="expense">
  <p>
    <%= link_to expense.user.name, expense.user %>
    paid <%= number_to_currency(expense.amount) %>
    for <%= link_to expense.name, expense %>
    (<%= link_to expense.category.name, expense.category %>)
    on <%= expense.created_at.strftime("%B %d, %Y") %>.
    <% if expense.shared? %>
      <strong>Shared!</strong>
    <% end %>
  </p>
</div>

app/views/expenses/_form.html.erb
<div>
  <%= form.label :name %>
  <%= form.text_field :name %>
</div>
<div>
  <%= form.label :amount %>
  <%= form.text_field :amount %>
</div>
<div>
  <%= form.label :category_id %>
  <%= form.select :category_id, Category.all.map { |category| [category.name, category.id] } %>
</div>
<div>
  <%= form.label :shared %>
  <%= form.check_box :shared %>
</div>

app/views/expenses/edit.html.erb
<h1>Edit Expense</h1>

<%= form_for @expense do |form| %>
  <%= render "form" , form: form %>
  <div>
    <%= form.submit "Update expense" %>
  </div>
<% end %>

app/views/expenses/index.html.erb
<h1>Expenses</h1>

<%= form_for @new_expense do |form| %>
  <%= render "form" , form: form %>
  <div>
    <%= form.submit "Create expense" %>
  </div>
<% end %>

<%= render @expenses %>

app/views/expenses/show.html.erb
<h1>Expense: <%= @expense.name %></h1>

<p>Amount: <%= number_to_currency(@expense.amount) %></p>
<p>Paid by: <%= @expense.user_name %></p>
<p>Category: <%= link_to @expense.category_name, @expense.category %></p>
<p>Shared: <%= @expense.shared? %></p>

<p>
  <%= link_to "Edit", edit_expense_path(@expense) %> |
  <%= link_to "Delete", expense_path(@expense), method: :delete %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= body_class %>">

  <nav>
    <ul>
      <% if signed_in? %>
        <%= link_to "Dashboard", dashboard_path %> |
        <%= link_to "Sign Out", session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign In", new_session_path %>
      <% end %>
    </ul>
  </nav>

  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
</body>
</html>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<%= render @user.expenses %>